/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tasks5_command_Application */

#ifndef _Included_com_tasks5_command_Application
#define _Included_com_tasks5_command_Application
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
